### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by Riizerr** [Clad3815/Twitch-Streamer-GPT#1]
Hello, I have a problem when I execute the start_all script
I have followed the steps to add the different api keys on Picovoice, open ai and eleven labs, but I have this message that appears:

No history file found
Error loading wake word: Error: No AccessKey provided to Porcupine
Failed to initialize: TypeError: Cannot read properties of undefined (reading 'frameLength')
C:\Program Files (x86)\Twitch-Streamer-GPT-main\modules\openaiLib.js:65
        throw new Error("Voice not found");
              ^

Error: Voice not found
    at Object.initVoice (C:\Program Files (x86)\Twitch-Streamer-GPT-main\modules\openaiLib.js:65:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.5.1

C:\Program Files (x86)\Twitch-Streamer-GPT-main>

Thx for your help

**Comment by Clad3815** [comment]
Hello, did you rename the `.env.example` into `.env` ?

**Comment by Riizerr** [comment]
Hello,
Yes i did it

Do You need anything ? A screen maybe ?

**Comment by Clad3815** [comment]
That's hard to say like that, it's really seem something is wrong with the configuration you did. And you can't send me the .env because it's sensitive data

**Comment by Clad3815** [comment]
Did you manage to fix it ?
