### ISSUE TITLE
Prompt pris en compte ?

### ISSUE THREAD

**Issue by luxman78** [Clad3815/Twitch-Streamer-GPT#10]
Hello,

J'ajoute des instructions dans le fichier custom_instructions.txt en lui demandant de répondre avec une haute dose d'humour mais il reste super sérieux pour ses réponses. 

Encore merci

**Comment by Clad3815** [comment]
Salut, tu as bien supprimé le "history.json" après avoir changé ? Car sinon l'IA va se baser sur ces anciennes réponses aussi. Sinon tu peux mettre le custom instructions ici que je vois ?

**Comment by luxman78** [comment]
voici le contenu de custom instructions : 
Tu réponds toujours en remerciant et avec une haute dose d'humour.

**Comment by luxman78** [comment]
bon il a pas bien la notion de 'haute d'ose d'humour' mais avec d'autres critères c'est ok. Merci
