### ISSUE TITLE
Rien ne se passe après la wake word answer

### ISSUE THREAD

**Issue by ZatoTV05** [Clad3815/Twitch-Streamer-GPT#23]
Bonjour,
J'ai un souci avec mon bot : il ne me répond pas après avoir fait la wakeword answer..
J'ai déjà regardé les autres post sur ce sujet mais je reste bloqué..

Voici ce que le bot m'affiche : 

Wake word loaded
Using microphone device: Microphone (2- Q9-1) | Wrong device? Run npm run choose-mic to select the correct input.
Please turn on microphone. Press any key to start 5 seconds of silence for calibration...
(node:15256) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ... to show where the warning was created)
Calibrating...
Calibration completed. SILENCE_THRESHOLD set to 16.15887628944175
Start listening
Wake word detected, start recording !
Playing from C:\Users\xavie\Twitch-Streamer-GPT\wake_word_answer: 5.mp3

Je n'ai pas l'impression que le Silence Threshold soit trop haut mais j'ai quand même essayer en activant le NODE VAD mais rien ne change.. Je ne sais pas trop comment faire du coup..

Voici ce que j'ai aussi comme message au niveau du bot twitch : 

Bot started and listening to channel zato__tv
(node:13200) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Twitch bot listening at http://localhost:3048/
Using OpenAI model gpt-3.5-turbo.
[2023-12-22T12:15:28.124Z] twurple:chat:twitch ERROR Error fetching a token for connecting to the server: Invalid token supplied

Qqun saurait-il m'aider ? Merci beaucoup !

**Comment by Clad3815** [comment]
Tu as l'erreur dans ton message `ERROR Error fetching a token for connecting to the server: Invalid token supplied` tu dois vérifier tes tokens pour Twitch dans le .env

**Comment by ZatoTV05** [comment]
Je viens de vérifier et les tokens sont bons normalement.. mais il m'affiche toujours ce message : 

Bot started and listening to channel zato__tv
(node:10796) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Twitch bot listening at http://localhost:3048
Using OpenAI model gpt-3.5-turbo.
[2023-12-22T12:40:03.822Z] twurple:chat:twitch ERROR Error fetching a token for connecting to the server: Invalid token supplied
[13:40] info: Connecting to irc-ws.chat.twitch.tv on port 443..
[13:40] info: Sending authentication to server..
[13:40] info: Connected to server.
[13:40] info: Executing command: JOIN #zato__tv
[13:40] info: Joined #zato__tv

**Comment by ZatoTV05** [comment]
My bad.. Je n'avais pas fait attention mais je n'avais pas mis au niveau du Twitch Bot Account.. Autant pour moi.
Tout est bon pour moi du coup ! Il ne me reste plus qu'à personnaliser un peu plus le bot !

merci Clad3815 pour ton aide !
