### ISSUE TITLE
The bot disconnect every time

### ISSUE THREAD

**Issue by CendresBleues** [Clad3815/Twitch-Streamer-GPT#3]
Hello , when i am starting the "start all file" all is working , but when i start to say the wake up word the chat bot give me error like a disconnexion the error is : [2023-08-14T04:54:09.765Z] twurple:pubsub:basic ERROR Disconnected unexpectedly: [1006]
and it does every minutes, the bot run , sometime say "merci d'avoir regarder cette vidéo " instead  of my sentence IDK Why.
Did you have a solution to stop disconnect ? 
(i have the same client id as my bot account on my main cause it's on the same email i guess) 
You can respond in french if you want , will be more simple if you speak it but english is good too.

![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/44650742/f767b94e-9de6-46d2-9044-6401377a8c7f)

**Comment by CendresBleues** [comment]
![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/44650742/11ca7768-c78e-468d-816b-b444d97c760a)
Sometimes , recognize just a "you" instead of my sentence

**Comment by CendresBleues** [comment]
Ok so the "you" word is created by a crack noise inside all my microphone , i dont hear them when hear on my voicemeeter but the bot create this noises

**Comment by Clad3815** [comment]
Can you try to use "node-vad" instead of the Silence Threshold system ? For that you need to activate it on the `.env` and start the .bat `install_node_vad.bat`

**Comment by CendresBleues** [comment]
Ok so the node vad working well , only problem is the disconnect

**Comment by Clad3815** [comment]
The disconnect seem to be from your internet or something, but normally it's auto reconnect. Did it produce some bugs ? Or just the logs on the console ?

**Comment by CendresBleues** [comment]
Did i need to change the port maybe ? i am using a 4g router can it be the problem ?

**Comment by Clad3815** [comment]
Can be, but I will check about that. I didn't tried on "slow" connexion. I think I can make a workaround

**Comment by CendresBleues** [comment]
Ok thank you my 4g is a slow connexion but my internet box is more slower xD

**Comment by Clad3815** [comment]
Haha yea I got that, otherwise no reason to use 4G. Actually the script have multiple opened connexion to twitch not a single one, so it's can be the case. I will do some test and update this issue

**Comment by CendresBleues** [comment]
Ok j'ai trouvé d'ou venait le soucis , je m'étais  raté dans la configuration , tout venais de moi hahaha désolé pour le derangement
