### ISSUE TITLE
Problème lors de l'installation

### ISSUE THREAD

**Issue by Socrqte** [Clad3815/Twitch-Streamer-GPT#7]
Hello !

Merci pour ce tuto, cependant j'ai un problème dès la première étape de l'installation après avoir téléchargé NodeJS.

Lorsque je lance install.bat (testé en normal et en mode admin au cas où), l'installation se lance puis à la fin j'ai une longue liste de messages d'erreur et de warning.

J'ai tenté quand même au cas où ensuite de lancer start_all.bat mais rien n'y fait il me lui aussi un message d'erreur. Est-ce un problème connu ? 

Merci d'avance !
Socrqte.

**Comment by Clad3815** [comment]
Il faut que tu me montre les lignes d'erreur après avoir lancé le `install.bat` que je vois le problème

**Comment by Socrqte** [comment]
Merci pour ta réponse !

Finalement j'ai réussi à régler le problème en réinstallant Visual Studio et un autre outil. Mais du coup j'ai un autre problème après l'installation et après avoir configuré les voix et le fichier .env

Lorsque j'exécute start_all.bat, tout se lance, je fais la calibration du silence, et il reconnait bien le wake_word, mais ensuite il n'entend pas ma question, ça ne bouge pas pendant 20min si j'en crois le fichier recording qui en sort et ensuite j'ai ces deux messages d'erreur sur le twitch bot et le voice recording. Il semblerait qu'il y ait un problème pour joindre OpenAI alors que j'ai bien mis la clé dans le fichier et tout.

![1](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/142446131/f1138d33-6646-4f41-b2ed-3ddcfe6b8852)
![2](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/142446131/1a86f0a2-562c-4991-9de7-5e54c05bba95)

**Comment by Clad3815** [comment]
Essaie d'activer "node-vad" lance le fichier bat d'install pour ça et active le dans le .env et dit moi si ça corrige le soucis. Pour OpenAI ça peut être a cause du quota quand tu as un compte gratuit les limites sont très basse. Tu peux ajouter un moyen de paiement sur OpenAI (Tu auras quand même les crédits gratuit à utiliser avant) mais tu auras un plus gros quota

**Comment by Socrqte** [comment]
Je viens de tester en activant node-vad sans moyen de paiement, aucun résultat. Node-vad avec moyen de paiement pareil. Et sans node-vad et AVEC moyen de paiement ça ne fonctionne pas non plus.

Je vais peut-être attendre un peu, histoire de voir s'il y a pas un petit temps avant que l'API capte que j'ai rajouté un moyen de paiement ou pas.

**Comment by Clad3815** [comment]
Active le mode debug dans le .env tu devrais voir le message d'erreur de OpenAI

**Comment by Socrqte** [comment]
Alors... J'ai réussi à régler le problème, et c'était une solution vraiment toute bête finalement.

Il fallait juste que ... je coupe mon micro après avoir posé la question. Et grâce à ça le recording s'arrête et est envoyé à l'API. 

Merci en tout cas pour ton aide ! Ça va bien me servir :)

**Comment by Clad3815** [comment]
Je vais faire une mise à jour pour améliorer la détection du "silence" pour détecter la fin de la question. Je ferme du coup :)
