### ISSUE TITLE
"Not enough credits or invalid API key"

### ISSUE THREAD

**Issue by Socrqte** [Clad3815/Twitch-Streamer-GPT#8]
Hello !

J'ai un nouveau problème, tout fonctionnait parfaitement et à un moment le bot a cessé de fonctionner. Il me renvoie le message suivant : 

"Unauthorized: Not enough credits or invalid API key."

J'ai tout checké, j'ai bien assez de crédits sur mon compte (vu que je paye que ce que j'utilise logiquement je devrais être large, puisque j'ai utilisé que 15ct de crédit sur les 120 dollars qu'il est possible d'utiliser), et j'ai tenté de changer ma clé d'API, mais rien n'y fait. Surtout qu'il me renvoie ce message, mais ça me compte quand même des utilisations sur OpenAI, je vois mon total de crédits monter. Dans le fichier .env y'a bien la ligne suivante : 

"Maximum number of tokens the API will return. 
Set to 0 for no limit.
 OPENAI_MAX_TOKENS_ANSWER= "" "

C'est peut être là le problème, j'avais mis 0 à la base comme indiqué, et quand je test, le bot me renvoie en message d'erreur qu'il faut au moins mettre 1. Et c'est en mettant 1 ou plus que j'ai le message "not enough credits..."

J'ai tenté aussi de mettre à jour le bot, et de refaire une installation clean, et le problème reste le même.

Si tu as une solution à ça, merci d'avance :) il a vraiment cessé de marcher en plein stream sans intervention de ma part du coup.

**Comment by Clad3815** [comment]
Salut, alors oui je viens de voir que c'est une erreur dans le .env seulement `OPENAI_MAX_TOKENS_TOTAL` peut être mis à 0, pour `OPENAI_MAX_TOKENS_ANSWER` je conseil une valeur entre 150 et 300 (300 c'est plus safe si tu créé des sondage ou autre)

Après l'erreur vient de Elevenlabs normalement le "Not enough credits or invalid API key" pas de OpenAI

**Comment by Socrqte** [comment]
J'allais justement dire que je venais de trouver la solution et que ça venait en effet d'ElevenLabs...

Je pensais pas avoir atteint aussi rapidement la limite mensuelle ! Merci pour ta réponse rapide !

**Comment by Clad3815** [comment]
Avec plaisir :) j'ai corrigé le texte dans .env pour éviter de faire l'erreur avec la valeur 0
